"""Alembic environment configuration for async SQLAlchemy (asyncpg).

CRITICAL: `version_table="ft_alembic_version"` is passed to both
`context.configure()` calls below. This service's migration chain lives in
the SAME physical Postgres database as applications/dashboard/backend, but
MUST NOT share that service's `alembic_version` bookkeeping table — doing so
would let either service's `alembic upgrade head` stamp/read the wrong
chain's current revision and corrupt the other's migration history.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# ── Import all models so their metadata is registered with Base ───────────────
# Each import registers the model's table in Base.metadata. If a model is
# missing here, its table will not appear in autogenerated migrations.
from app.database.session import Base  # noqa: F401
from app.models.tracking_set import TrackingSet  # noqa: F401
from app.models.category import Category  # noqa: F401
from app.models.sub_category import SubCategory  # noqa: F401
from app.models.tracking_item import TrackingItem  # noqa: F401
from app.models.initial_investment_entry import InitialInvestmentEntry  # noqa: F401

# ── Alembic Config object ─────────────────────────────────────────────────────
config = context.config

# Interpret the config file for Python logging — this line sets up loggers.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Use Base.metadata as the target for autogenerate
target_metadata = Base.metadata

# See module docstring — keeps this chain's bookkeeping isolated from the
# main backend's "alembic_version" table in the same database.
VERSION_TABLE = "ft_alembic_version"


def get_url() -> str:
    """Read DATABASE_URL from environment. Required — no fallback."""
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "DATABASE_URL environment variable is not set. "
            "Example: postgresql+asyncpg://user:pass@localhost:5432/dbname"
        )
    return url


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine.
    Calls to context.execute() here emit the given string to the
    script output.
    """
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        version_table=VERSION_TABLE,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        version_table=VERSION_TABLE,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations using an async engine (required for asyncpg)."""
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = get_url()

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode with an async engine."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
