"""Shared utilities, prompts, and tools."""

from .prompts import (
    AI_SYSTEM,
    API_SYSTEM,
    BACKEND_LEAD_SYSTEM,
    CHIEF_ARCHITECT_SYSTEM,
    DATABASE_SYSTEM,
    DEVOPS_SYSTEM,
    ENTERPRISE_CODE_STANDARDS,
    FRONTEND_LEAD_SYSTEM,
    PERFORMANCE_SYSTEM,
    PLATFORM_CONTEXT,
    QA_SYSTEM,
    RESPONSIVE_SYSTEM,
    SECURITY_SYSTEM,
    SKILLS_SYSTEM,
    UIUX_SYSTEM,
)
from .tools import SHARED_TOOLS
from .utils import (
    build_task_payload,
    content_hash,
    dedent_code,
    extract_code_blocks,
    format_duration,
    slugify,
    truncate,
)

__all__ = [
    "AI_SYSTEM",
    "API_SYSTEM",
    "BACKEND_LEAD_SYSTEM",
    "CHIEF_ARCHITECT_SYSTEM",
    "DATABASE_SYSTEM",
    "DEVOPS_SYSTEM",
    "ENTERPRISE_CODE_STANDARDS",
    "FRONTEND_LEAD_SYSTEM",
    "PERFORMANCE_SYSTEM",
    "PLATFORM_CONTEXT",
    "QA_SYSTEM",
    "RESPONSIVE_SYSTEM",
    "SECURITY_SYSTEM",
    "SKILLS_SYSTEM",
    "UIUX_SYSTEM",
    "SHARED_TOOLS",
    "build_task_payload",
    "content_hash",
    "dedent_code",
    "extract_code_blocks",
    "format_duration",
    "slugify",
    "truncate",
]
