"""add symbol_notes table

Revision ID: a6bcb833f755
Revises: 
Create Date: 2026-06-01 10:04:06.473195+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6bcb833f755'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symbol_notes', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('symbol_notes', 'asset_type')
    op.drop_column('symbol_notes', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol_notes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('symbol_notes', sa.Column('asset_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.alter_column('symbol_notes', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
